// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// perimeter_cpp
double perimeter_cpp(const IntegerMatrix& x);
RcppExport SEXP _EBImageExtra_perimeter_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(perimeter_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// circularity_cpp
double circularity_cpp(const IntegerMatrix& x);
RcppExport SEXP _EBImageExtra_circularity_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(circularity_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// crop_cpp
NumericMatrix crop_cpp(const NumericMatrix& img, int border, double fill);
RcppExport SEXP _EBImageExtra_crop_cpp(SEXP imgSEXP, SEXP borderSEXP, SEXP fillSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type border(borderSEXP);
    Rcpp::traits::input_parameter< double >::type fill(fillSEXP);
    rcpp_result_gen = Rcpp::wrap(crop_cpp(img, border, fill));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EBImageExtra_perimeter_cpp", (DL_FUNC) &_EBImageExtra_perimeter_cpp, 1},
    {"_EBImageExtra_circularity_cpp", (DL_FUNC) &_EBImageExtra_circularity_cpp, 1},
    {"_EBImageExtra_crop_cpp", (DL_FUNC) &_EBImageExtra_crop_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_EBImageExtra(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
