# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

perimeter_cpp <- function(x) {
    .Call(`_EBImageExtra_perimeter_cpp`, x)
}

circularity_cpp <- function(x) {
    .Call(`_EBImageExtra_circularity_cpp`, x)
}

crop_cpp <- function(img, border = 1L, fill = 0.0) {
    .Call(`_EBImageExtra_crop_cpp`, img, border, fill)
}

